# Generated by Django 5.0.6 on 2024-06-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('likes_count', models.CharField(blank=True, max_length=50, null=True)),
                ('posting_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape_linkedin.linkedinusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='linkedInPostLikeDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape_linkedin.linkedinpostmodel')),
                ('liker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape_linkedin.linkedinusermodel')),
            ],
        ),
    ]
